### ISSUE TITLE
FlamePaper 1.8.8 - 

### ISSUE THREAD

**Issue by rejomy** [kit8379/SyncCommand#1]
[19:28:03 ERROR]: Could not load 'plugins/SyncCommand-1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/me/synccommand/bukkit/SyncCommandBukkit has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:190) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.UnsupportedClassVersionError: org/me/synccommand/bukkit/SyncCommandBukkit has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_312]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_312]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_312]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_312]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[server.jar:git-PaperSpigot-e7c34e5f]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-PaperSpigot-e7c34e5f]
        ... 6 mor

**Comment by rejomy** [comment]
If I change the version on the hosting, on java 11 it writes this error: https://paste.md-5.net/epuzixuvig.md

**Comment by rejomy** [comment]
and stop... This plugin is not suitable for hosting?

**Comment by kit8379** [comment]
It seems like i have used a configuration API which is not suitable for 1.8.8 API. I will fix it tmr.
But yes Java11 is required, does you hosting still using Java8?

**Comment by rejomy** [comment]
> It seems like i have used a configuration API which is not suitable for 1.8.8 API. I will fix it tmr.
> But yes Java11 is required, does you hosting still using Java8?

No, I can put it at 11. 

"If I change the version on the hosting, on java 11 it writes this error: https://paste.md-5.net/epuzixuvig.md"

**Comment by kit8379** [comment]
Okay. I will fix it tmr. Thank you for supporting this plugin.

**Comment by rejomy** [comment]
Okay, but I still have a question. I'm using a hosting service and the most I can do here is to take an extra port. How do I connect to Redis and could you add the ability to create connections via ip and port + password?

**Comment by kit8379** [comment]
It can be configured in config.yml

**Comment by rejomy** [comment]
> It can be configured in config.yml

https://paste.md-5.net/vaqovapasa.md

**Comment by kit8379** [comment]
> > It can be configured in config.yml
> 
> https://paste.md-5.net/vaqovapasa.md

Hello. I am not yet fixed. Can you wait for few days more?

**Comment by kit8379** [comment]
> > It can be configured in config.yml
> 
> https://paste.md-5.net/vaqovapasa.md

Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.

**Comment by rejomy** [comment]
> > > It can be configured in config.yml
> > 
> > 
> > https://paste.md-5.net/vaqovapasa.md
> 
> Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.

Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?

**Comment by kit8379** [comment]
> > > > It can be configured in config.yml
> > > 
> > > 
> > > https://paste.md-5.net/vaqovapasa.md
> > 
> > 
> > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> 
> Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?

No. It must required Redis now.
You want simply Bungee Messaging to do this?

**Comment by rejomy** [comment]
> > > > > It can be configured in config.yml
> > > > 
> > > > 
> > > > https://paste.md-5.net/vaqovapasa.md
> > > 
> > > 
> > > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> > 
> > 
> > Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?
> 
> No. It must required Redis now. You want simply Bungee Messaging to do this?

Let's do it again:
- I have a server that is hosted, all I can get from hosting is an extra port.
- I want to send commands from lobby to server1-2 and have server1-2 execute those commands, that's it.

**Comment by kit8379** [comment]
> > > > > > It can be configured in config.yml
> > > > > 
> > > > > 
> > > > > https://paste.md-5.net/vaqovapasa.md
> > > > 
> > > > 
> > > > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> > > 
> > > 
> > > Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?
> > 
> > 
> > No. It must required Redis now. You want simply Bungee Messaging to do this?
> 
> Let's do it again:
> 
> * I have a server that is hosted, all I can get from hosting is an extra port.
> * I want to send commands from lobby to server1-2 and have server1-2 execute those commands, that's it.

Okay. I got it. You are using server hosting system like McProHosting style, which only host each minecraft server individually.
I will add Bungee Messaging support later.

**Comment by rejomy** [comment]
> > > > > > > It can be configured in config.yml
> > > > > > 
> > > > > > 
> > > > > > https://paste.md-5.net/vaqovapasa.md
> > > > > 
> > > > > 
> > > > > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> > > > 
> > > > 
> > > > Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?
> > > 
> > > 
> > > No. It must required Redis now. You want simply Bungee Messaging to do this?
> > 
> > 
> > Let's do it again:
> > 
> > * I have a server that is hosted, all I can get from hosting is an extra port.
> > * I want to send commands from lobby to server1-2 and have server1-2 execute those commands, that's it.
> 
> Okay. I got it. You are using server hosting system like McProHosting style, which only host each minecraft server individually. I will add Bungee Messaging support later.

Ok, just fyi, all other plugins just don't work, some can't start properly, others drop the connection after n amount of time.

**Comment by rejomy** [comment]
Also such a ridiculous question, how long is the wait?

**Comment by kit8379** [comment]
> > > > > > > > It can be configured in config.yml
> > > > > > > 
> > > > > > > 
> > > > > > > https://paste.md-5.net/vaqovapasa.md
> > > > > > 
> > > > > > 
> > > > > > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> > > > > 
> > > > > 
> > > > > Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?
> > > > 
> > > > 
> > > > No. It must required Redis now. You want simply Bungee Messaging to do this?
> > > 
> > > 
> > > Let's do it again:
> > > 
> > > * I have a server that is hosted, all I can get from hosting is an extra port.
> > > * I want to send commands from lobby to server1-2 and have server1-2 execute those commands, that's it.
> > 
> > 
> > Okay. I got it. You are using server hosting system like McProHosting style, which only host each minecraft server individually. I will add Bungee Messaging support later.
> 
> Ok, just fyi, all other plugins just don't work, some can't start properly, others drop the connection after n amount of time.

I don't understand. What meant by all other plugins just don't work. Other plugins should not related to my plugin.

**Comment by rejomy** [comment]
> > > > > > > > > It can be configured in config.yml
> > > > > > > > 
> > > > > > > > 
> > > > > > > > https://paste.md-5.net/vaqovapasa.md
> > > > > > > 
> > > > > > > 
> > > > > > > Hello. I have just uploaded a bug fixed version. May you please try it out to see if it works or not? Thank you.
> > > > > > 
> > > > > > 
> > > > > > Hi. Yes, it works, but there is an error https://paste.md-5.net/pawokibawa.md and here's a question, how do I set this up without redis?
> > > > > 
> > > > > 
> > > > > No. It must required Redis now. You want simply Bungee Messaging to do this?
> > > > 
> > > > 
> > > > Let's do it again:
> > > > 
> > > > * I have a server that is hosted, all I can get from hosting is an extra port.
> > > > * I want to send commands from lobby to server1-2 and have server1-2 execute those commands, that's it.
> > > 
> > > 
> > > Okay. I got it. You are using server hosting system like McProHosting style, which only host each minecraft server individually. I will add Bungee Messaging support later.
> > 
> > 
> > Ok, just fyi, all other plugins just don't work, some can't start properly, others drop the connection after n amount of time.
> 
> I don't understand. What meant by all other plugins just don't work. Other plugins should not related to my plugin.

What I mean is that other plugins that are supposed to establish a connection between servers and listen for commands just don't work. Your plugin was not the first one I found, but it seems to be the last hope.

**Comment by kit8379** [comment]
No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it.
Are you using BungeeCord?

**Comment by rejomy** [comment]
> No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?

I use velocity

**Comment by kit8379** [comment]
> > No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?
> 
> I use velocity

Ok. Same approach.

I will add it work without Redis. Probably will be done in tmr.

**Comment by rejomy** [comment]
> > > No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?
> > 
> > 
> > I use velocity
> 
> Ok. Same approach.
> 
> I will add it work without Redis. Probably will be done in tmr.

Maybe I'm imagining this wrong, but does a plugin have to have some sort of proxy? Why not make a connection between two spigot servers?

**Comment by kit8379** [comment]
> 

It is because you are not able to do it. Make a connection between two spigot servers require additional port, which is not available in hosting service.

**Comment by kit8379** [comment]
> > > > No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?
> > > 
> > > 
> > > I use velocity
> > 
> > 
> > Ok. Same approach.
> > I will add it work without Redis. Probably will be done in tmr.
> 
> Maybe I'm imagining this wrong, but does a plugin have to have some sort of proxy? Why not make a connection between two spigot servers?

However, using bungee messaging have a disadvantage. At least a player has to be online in the proxy to make the plugin works. Therefore, I will add SQL messaging also. Although it is not the best approach. The best approach is using Redis.

Making a connection between two spigot servers is also not a good approach. It required additional port open.

**Comment by kit8379** [comment]
> > > > No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?
> > > 
> > > 
> > > I use velocity
> > 
> > 
> > Ok. Same approach.
> > I will add it work without Redis. Probably will be done in tmr.
> 
> Maybe I'm imagining this wrong, but does a plugin have to have some sort of proxy? Why not make a connection between two spigot servers?

Hello. Can you give your opinion out

**Comment by rejomy** [comment]
> > > > > No. This plugin does not directly "establish a connection between servers". It use Pub/Sub messaging system to achieve it. Are you using BungeeCord?
> > > > 
> > > > 
> > > > I use velocity
> > > 
> > > 
> > > Ok. Same approach.
> > > I will add it work without Redis. Probably will be done in tmr.
> > 
> > 
> > Может быть, я неправильно себе это представляю, но должен ли плагин иметь какой-то прокси? Почему бы не установить соединение между двумя патрубковыми серверами?
> 
> Hello. Can you give your opinion out

Almost all NOT free hosting gives extra ports, if your plugin will be able to do it without the extra port, that will be fine, but it makes no difference to me in general whether to use the extra port or not. I think it is more convenient to synchronize via velocity, I imagine it like this: my spigot server is bound to rcon, I send a command when I buy a privilege and it is executed on all available servers.

**Comment by kit8379** [comment]
> 

I suggest using velocity (bungee messaging) if you don’t mind the limitation of having at least a player online to make it works.

**Comment by rejomy** [comment]
> > 
> 
> I suggest using velocity (bungee messaging) if you don’t mind the limitation of having at least a player online to make it works.

I need the plugin to issue currency, privileges, some kind of set or commands. If I understand you correctly and players 100% will get the goods, then yes, everything is just perfect.

**Comment by rejomy** [comment]
@kit8379 how's it going?

**Comment by rejomy** [comment]
@kit8379 how's it going?

**Comment by rejomy** [comment]
@kit8379 how's it going?

**Comment by rejomy** [comment]
@kit8379 how's it going?

**Comment by rejomy** [comment]
I realize you have your studies, your personal life, but please give me at least 20 minutes of your time.

**Comment by kit8379** [comment]
> I realize you have your studies, your personal life, but please give me at least 20 minutes of your time.

Sorry. I am busy in this few weeks. I need more time to have it finished.
I will notice you at the time when I completed it.
