### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 2006lev-Web** [kit8379/SyncCommand#2]
`[07:32:18] [main/INFO] [com.velocitypowered.proxy.Velocity]: Done (9.32s)!
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.Connection.connect(Connection.java:188)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:374)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.Connection.<init>(Connection.java:61)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.Jedis.<init>(Jedis.java:214)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:178)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.me.synccommand.shared.RedisHandler.subscribe(RedisHandler.java:31)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at org.me.synccommand.shared.RedisPubSub.lambda$init$1(RedisPubSub.java:46)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	Suppressed: java.net.ConnectException: Connection refused
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at java.base/java.net.Socket.connect(Socket.java:633)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:73)
[07:32:18] [Thread-3/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 		... 14 more
[07:32:18] [CaptchaGeneratorThread/INFO] [limbofilter]: Captcha generated in 2978 ms.`

**Comment by kit8379** [comment]
Have you installed Redis. It shows that the connection to Redis server is not successful

**Comment by 2006lev-Web** [comment]
and without it there is no place I use regular Minecraft hosting
