### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by xiaoluofa** [kit8379/SyncCommand#3]
[21:02:22 INFO]: _Kamisat0Ayaka_ issued server command: /sync channel1 o reload all
[21:02:22 WARN]: java.lang.UnsupportedOperationException
[21:02:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
[21:02:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
[21:02:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
[21:02:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
[21:02:22 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//org.me.synccommand.bukkit.BukkitConsoleCommand.executeCommand(BukkitConsoleCommand.java:15)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//org.me.synccommand.shared.RedisPubSub$1.onMessage(RedisPubSub.java:42)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:156)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:125)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//redis.clients.jedis.Jedis.subscribe(Jedis.java:7993)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//org.me.synccommand.shared.RedisHandler.subscribe(RedisHandler.java:32)
[21:02:22 WARN]:        at SyncCommand-1.0.jar//org.me.synccommand.shared.RedisPubSub.lambda$init$1(RedisPubSub.java:46)
[21:02:22 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:02:24 INFO]: dakuang lost connection: Disconnected

**Comment by kit8379** [comment]
I made an update. Please try the new version to see whether the issue is still exist or not. Thank you.

**Comment by xiaoluofa** [comment]
no fix
[16:58:34 INFO]: _Kamisat0Ayaka_ issued server command: /sync channel1 o reload all
[16:58:34 WARN]: java.lang.UnsupportedOperationException
[16:58:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
[16:58:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
[16:58:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
[16:58:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
[16:58:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
[16:58:34 WARN]:        at SyncCommand.jar//org.me.synccommand.bukkit.BukkitConsoleCommand.executeCommand(BukkitConsoleCommand.java:15)
[16:58:34 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:43)
[16:58:34 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:40)
[16:58:34 WARN]:        at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.process(JedisPubSubBase.java:139)
[16:58:34 WARN]:        at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.proceed(JedisPubSubBase.java:92)
[16:58:34 WARN]:        at SyncCommand.jar//redis.clients.jedis.Jedis.subscribe(Jedis.java:7941)
[16:58:34 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisHandler.lambda$subscribe$1(RedisHandler.java:36)
[16:58:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:58:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[16:58:34 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:58:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:58:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:58:34 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:58:34 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:58:34 INFO]: [PillageEventTracker] guguitibankawaii 触发了一次袭击事件在: X:-4534, Y:71, Z:8183
[16:58:40 INFO]: MC_shaoyan issued server command: /brtp
[16:58:42 ERROR]: [redis.clients.jedis.JedisFactory] Error while validating pooled Jedis object.
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [B (java.util.ArrayList and [B are in module java.base of lo
ader 'bootstrap')
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:268) ~[SyncCommand.jar:?]
        at redis.clients.jedis.Jedis.ping(Jedis.java:339) ~[SyncCommand.jar:?]
        at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:198) ~[SyncCommand.jar:?]
        at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:748) ~[SyncCommand.jar:?]
        at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:162) ~[SyncCommand.jar:?]
        at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:115) ~[SyncCommand.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
![image](https://github.com/kit8379/SyncCommand/assets/75927411/bae5294f-6a05-40b5-ab3f-452959d4b742)

**Comment by xiaoluofa** [comment]
command can sync to paper,but folia dont work

**Comment by kit8379** [comment]
Ok. So this error is happening in folia server?

**Comment by xiaoluofa** [comment]
> Ok. So this error is happening in folia server?

yes

**Comment by xiaoluofa** [comment]
![image](https://github.com/kit8379/SyncCommand/assets/75927411/70bb3b5f-c387-452e-8cc6-ed541a4b5a95)
velocity cant work

**Comment by kit8379** [comment]
> > Ok. So this error is happening in folia server?
> 
> yes

Folia is not support yet.

**Comment by kit8379** [comment]
> ![image](https://private-user-images.githubusercontent.com/75927411/320251899-70bb3b5f-c387-452e-8cc6-ed541a4b5a95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjU1MzEsIm5iZiI6MTcxMzAyNTIzMSwicGF0aCI6Ii83NTkyNzQxMS8zMjAyNTE4OTktNzBiYjNiNWYtYzM4Ny00NTJlLThjYzYtZWQ1NDFhNGI1YTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDE2MjAzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MTE1NWE1MTI0NGI0ZTY0MmZjOWJmNThiNDNlZjg5ODhjNTJlYjc2MzdkZjFkM2RiYjcxZmQ0ZWI0MGE1YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BohW-EJGGa40bewkMxCTo7dQzAB-VIz0U0yiCs1L50Y) velocity cant work

Please temporary use the previous version. I will fix all of this problem in May.

**Comment by xiaoluofa** [comment]
Looking forward to your update

**Comment by 404forever1** [comment]
The latest version is not folia compatible.

**Comment by kit8379** [comment]
> The latest version is not folia compatible.

Folia is not yet supported. I am not familiar with their API yet. Please wait. Thank you.

**Comment by 404forever1** [comment]
> > The latest version is not folia compatible.
> 
> Folia is not yet supported. I am not familiar with their API yet. Please wait. Thank you.

velocity fixed

**Comment by kit8379** [comment]
Added Folia support.

**Comment by 404forever1** [comment]
> Added Folia support.

nice

**Comment by 404forever1** [comment]
Still does not seem to support folia, missing folia-supported: true

**Comment by 404forever1** [comment]
[15:23:09 WARN]: java.lang.UnsupportedOperationException
[15:23:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535)
[15:23:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235)
[15:23:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211)
[15:23:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175)
[15:23:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144)
[15:23:09 WARN]:        at SyncCommand.jar//org.me.synccommand.bukkit.BukkitConsoleCommand.executeCommand(BukkitConsoleCommand.java:15)
[15:23:09 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:43)
[15:23:09 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:40)
[15:23:09 WARN]:        at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.process(JedisPubSubBase.java:139)
[15:23:09 WARN]:        at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.proceed(JedisPubSubBase.java:92)
[15:23:09 WARN]:        at SyncCommand.jar//redis.clients.jedis.Jedis.subscribe(Jedis.java:7941)
[15:23:09 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisHandler.subscribe(RedisHandler.java:32)
[15:23:09 WARN]:        at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub.lambda$init$1(RedisPubSub.java:47)
[15:23:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by kit8379** [comment]
> Still does not seem to support folia, missing folia-supported: true

I will have a look now.

**Comment by kit8379** [comment]
> [15:23:09 WARN](java.lang.UnsupportedOperationException): at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) [15:23:09 WARN](java.lang.UnsupportedOperationException): at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) [15:23:09 WARN](java.lang.UnsupportedOperationException): at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) [15:23:09 WARN](java.lang.UnsupportedOperationException): at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) [15:23:09 WARN](java.lang.UnsupportedOperationException): at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//org.me.synccommand.bukkit.BukkitConsoleCommand.executeCommand(BukkitConsoleCommand.java:15) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:43) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub$1.onMessage(RedisPubSub.java:40) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.process(JedisPubSubBase.java:139) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//redis.clients.jedis.JedisPubSubBase.proceed(JedisPubSubBase.java:92) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//redis.clients.jedis.Jedis.subscribe(Jedis.java:7941) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//org.me.synccommand.shared.redis.RedisHandler.subscribe(RedisHandler.java:32) [15:23:09 WARN](java.lang.UnsupportedOperationException): at SyncCommand.jar//org.me.synccommand.shared.redis.RedisPubSub.lambda$init$1(RedisPubSub.java:47) [15:23:09 WARN](java.lang.UnsupportedOperationException): at java.base/java.lang.Thread.run(Thread.java:1583)

Hello. I fixed the problem and making sure it supports Folia now. Please update the plugin to version 1.2.2. Thank you for your patient.
