### ISSUE TITLE
Console Error when stopping a server

### ISSUE THREAD

**Issue by SentorCraft** [kit8379/SyncCommand#4]
[00:00:48] [Craft Scheduler Thread - 10 - SyncCommand/WARN]: [SyncCommand] Plugin SyncCommand v1.0 generated an exception while executing task 2036
java.lang.NoClassDefFoundError: org/me/synccommand/shaded/redis/clients/jedis/util/IOUtils
	at org.me.synccommand.shaded.redis.clients.jedis.Connection.disconnect(Connection.java:247) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.Connection.close(Connection.java:232) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.Jedis.close(Jedis.java:300) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:159) ~[SyncCommand.jar:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:127) ~[SyncCommand.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:610) ~[SyncCommand.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:454) ~[SyncCommand.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:1101) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.util.Pool.returnResource(Pool.java:51) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.JedisPool.returnResource(JedisPool.java:388) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.JedisPool.returnResource(JedisPool.java:17) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.redis.clients.jedis.Jedis.close(Jedis.java:297) ~[SyncCommand.jar:?]
	at org.me.synccommand.shared.redis.RedisHandler.subscribe(RedisHandler.java:32) ~[SyncCommand.jar:?]
	at org.me.synccommand.bukkit.SyncCommandBukkit.lambda$initialize$0(SyncCommandBukkit.java:57) ~[SyncCommand.jar:?]
	at org.me.synccommand.shaded.com.tcoded.folialib.impl.SpigotImplementation.lambda$runAsync$1(SpigotImplementation.java:51) ~[SyncCommand.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.me.synccommand.shaded.redis.clients.jedis.util.IOUtils
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 21 more

**Comment by kit8379** [comment]
Fixed
